### ISSUE TITLE
Na homepage přidat tlačítko Aktuality

### ISSUE THREAD

**Issue by karmi** [cesko-digital/pomahejukrajine-web#1]
Abychom mohli na stránce publikovat novinky a jiné důležité informace, potřebujeme odkaz nebo tlačítko _Aktuality_.

Odkaz povede buď na stránku aktuality v rámci webu, jejíž obsah můžeme sami spravovat, nebo na určitou stránku na webu [Konsorcia](https://migracnikonsorcium.cz).

<img width="1274" alt="menu" src="https://user-images.githubusercontent.com/4790/159009472-49832315-b21f-4ff6-9903-754267b5ee3b.png">

(Toto je ukázkové issue vytvořené v rámci tutorialu.)

**Comment by ZdenekMen** [comment]
zatim prosim nezpracovavat, pripravuje se komepletni redesign Homepage

**Comment by ZdenekMen** [comment]
test, zda mi to prijde do mailu 1 - bez mention

**Comment by ZdenekMen** [comment]
test, zda mi to pride do mailu s mention @ZdenekMen

**Comment by ZdenekMen** [comment]
2. pokus test, zda mi to prijde do mailu 1 - bez mention

**Comment by ZdenekMen** [comment]
2. pokus - test, zda mi to pride do mailu s mention @ZdenekMen
