### ISSUE TITLE
Redesign Nabidky pomoci – podpurne fce  - •	dodat ikony (to Hanka udela, ma je od Davida, jenom jeste od vcera nemela prostor)

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#100]

**Comment by hanny21** [comment]
pridat ikonky k typum nabidek na strance s verejnumi a neverejnymi nabidkami:
![image](https://user-images.githubusercontent.com/31318129/171144046-d8014e83-c5f1-4b19-be1a-1c79d2060660.png)
![image](https://user-images.githubusercontent.com/31318129/171144101-7b92e195-2ae8-4f9c-833e-99e38da990a3.png)
