### ISSUE TITLE
Redesign Nabidky pomoci – podpurne fce -•	predelat filtry - pro kraje + dalsi filtry pro nektere typy nabidek

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#101]

**Comment by ZdenekMen** [comment]
Ahoj Mateji @matej-sveda , prosím tě, můžeš ještě mrknout na to, že po prvním zavolání, ze zobrazí text, který sem nepatří. Po výběru konkrétní Kategorie nabídky zmizí. Díky moc.


![Image](https://user-images.githubusercontent.com/101886400/173565607-e267979d-d659-49f5-8743-48c84b5bc93e.png)

**Comment by matej-sveda** [comment]
Ahoj @ZdenekMen, to je tim uuid v URL. Defaultne ma byt vybrana nejaka kategorie a to nam prave rika to uuid, ktere by v tomto preipade melo patrit Doprave...na localhostu pouzivam produkcni udaje k contemberu a funguje to bez problemu...naopak kdyz si na stagingu zkopituju to uuid, ktery tam je po kliku na Dopravu, tak mi to naopak nefunguje na localhostu / na produkci... takze mam podezreni ze ty uuid katergorii jsou jine na produkci jako na stagingu...coz by nakonec nemusel byt problem, akorat to na stagingu proste bude takto blbnout... @honzasladek  muzes mi prosim tu teorii potvrdit / vyvratit?

**Comment by ZdenekMen** [comment]
Ahoj Matěji, @matej-sveda , diky moc za vysvětlení. OK - počkáme si na produkci a/nebo na Honzu. Přeji pěkný den

**Comment by ZdenekMen** [comment]
Ahoj Mateji @matej-sveda, prosim te jeste o jednu jednoduchou upravu. Odstranit to horni pole na hledani. Viz sipka. Patri to, k Globalnimu vyhledavani, ktere asi nestihneme a pokud ano, stejne by bylo nekde v Hlavicce uplne  nahore. Zde zustane jen to vlevo nad temi Filtry Moc dekuji

![image](https://user-images.githubusercontent.com/101886400/174045016-ed0e44d2-1fa4-418c-b4cc-341704dc0d90.png)

**Comment by matej-sveda** [comment]
a je, to se asi bloudila chybucka pri reseni konfliktu, hned to umazu..diky za upozorneni @ZdenekMen
