### ISSUE TITLE
Redesign Nabidky pomoci – podpurne fce - •	karticka s nabidkou pomoci - je treba upravit data, ktera se zobrazuji + modal s detailem nabidky

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#102]

**Comment by hanny21** [comment]
zmenit obsah karty s nabidkou pomoci
![image](https://user-images.githubusercontent.com/31318129/171144368-1db234c0-fbe4-4232-959a-97f2b0746150.png)

po kliku na tlacitka se zobrazi modal (v pripade kliku na Mam zajem se zobrazi v modalu krok c.2, tj. formular)
![image](https://user-images.githubusercontent.com/31318129/171144684-9fa5e104-d189-4460-889c-14fea084c07f.png)

pozn. obrazky zatm nejsou implementovane a mobilni verze je k dispozici ve firme

**Comment by martinsik** [comment]
@ZdenekMen Tento issue se tyka jenom toho gridu s kartami a modal okna s detailem nabidky nebo to zahrnuje i ty filtry co jsou nahore a vlevo?

**Comment by ZdenekMen** [comment]
Ahoj @martinsik , diky, ze jsi potom skočil ty, protože ty filtry řeší  @matej-sveda  se kterým uz umíte spolupracovat. Ze jednaní s Matějem, Honzou a Davidem a následným projednání v Konsorciu přidávám máme ještě upřesnění:
Pro  nový design zobrazovaných dlaždic nabídek byly navržena nová pole 
-	Název nabídky, který Honza vytvořil v datovém modelu a zajistí jeho naplnění, zatím se tedy zobrazí prázdné
-	Popis nabídky bude vytvářen specificky dle Kategorie nabídky. Pravidlo pro jeho tvorbu dodáme do zítřka 2.6.2022. Zatím to prosím můžete nechat prázdné.
-	Plus bychom prosili  dát dolu na dlaždici Kód nabídky.

**Comment by ZdenekMen** [comment]
Ahoj Martine, @Martin Sikora, napsal jsme to do slacku, ale aby se to neztratilo, dávám to ještě sem - dnes poo jsme si dojasňovali s UX vzhled té dlaždice: pánové to ještě domyslí, ale pokud by sis to chtěl už připravovat - bude to rámcově takto:
pevná velikost dlaždice  ,
zobrazí se název a potom postupně první parametry každé Kategorie nabídky a tož až do velikosti nějaké definované velikosti, zbytek se uřízne 
po zvolení Detail se ukáží všechny parametry - tak jak je tomu dnes.
Nakreslené a vyladěné to bude počátkem příštího týdne. Děkuji za pochopení. 
![Image](https://user-images.githubusercontent.com/101886400/171879836-07463a34-2868-4bd6-90bc-afec2165f069.png)

**Comment by martinsik** [comment]
![102-modal](https://user-images.githubusercontent.com/238765/173306073-8d8760c9-4f69-4ac8-a4b0-53d02d10426a.png)
![102-modal-2](https://user-images.githubusercontent.com/238765/173306074-f95b0392-5394-4499-9c7b-f917398c5cbd.png)
![102-modal-3](https://user-images.githubusercontent.com/238765/173306076-8555c19a-7705-4ca3-8dd9-23fc36e195bc.png)
![102-modal-4](https://user-images.githubusercontent.com/238765/173306077-444334fa-0c3f-4366-bce2-542d1073df0a.png)

**Comment by ZdenekMen** [comment]
Martine, @martinsik , díky - perfektní

**Comment by ZdenekMen** [comment]
Ahoj Martine @martinsik , moc se omlouvám, ale až dnes jsem objevil, že jsem ti schválil  chybnou kartičku jinak než bylo v návrhu tj bez možnosti dodat zprávu. Prosím tě, myslíš, že na to najdeš čas? To by tam chybělo Moc děkuji Viz


![Image](https://user-images.githubusercontent.com/101886400/174593630-6ada8bcc-adcd-4eac-8c0f-f0f929fc7baa.png)

**Comment by ZdenekMen** [comment]
Ahoj Martine @martinsik , promiň, mám ještě jeden dotaz, připomínku  -  nešlo by zobrazovat na stránce Nabídky pomoci vždy stejný počet karet tj 12 - 3x4 na obrazovce s filtry a 16 4x4 na obrazovce, kdy jsou filtry  schované?  Teď se jejich  počet různí.  moc děkuji

**Comment by ZdenekMen** [comment]
Ahoj @martinsik , díky moc, rozumím, také mi teď došlo, že bychom ji ještě potřebovali dostat i do mailu pro Nabízejícího. A to  vše narychlo nezvládneme. Víme ale jak na to tj dobrá příprava pro další fázi.  Dávám si to na cc @ZdenekMen, abych na to nezpomel
