### ISSUE TITLE
korektura 2 - Kategorie pomoci mají být na telefonu jako rozevírací seznam

### ISSUE THREAD

**Issue by Michal-Miky-Jankovsky** [cesko-digital/pomahejukrajine-web#123]
Nahoře je návrh, dole současný stav
Opět v zájmu toho, aby uživatel nemusel zbytečně scrollovat – toto má být rozevírací seznam, který uživatel rozklikne jen když potřebuje využít tento typ filtru.

![Image](https://user-images.githubusercontent.com/7955666/178517232-265d9add-0b3f-40fe-83d1-37219579e241.JPG)

![Image](https://user-images.githubusercontent.com/7955666/178517251-c8275758-95ad-47ea-bdc5-cee01d326a33.JPG)

**Comment by Michal-Miky-Jankovsky** [comment]
improve label / text of the collapse handle / dropdown

**Comment by Michal-Miky-Jankovsky** [comment]
waiting for graphical proposal - modal 
should be ready on Friday

**Comment by hanny21** [comment]
![image](https://user-images.githubusercontent.com/31318129/185806022-c61b505a-bbe7-4db4-9e68-05f22170bd35.png)
