### ISSUE TITLE
kategorie pomoci na mobilu - filtry

### ISSUE THREAD

**Issue by hanny21** [cesko-digital/pomahejukrajine-web#140]
dodelat informaci o tom, kolik nabidek odpovida zadani filtru na mobilu

![image](https://user-images.githubusercontent.com/31318129/196425148-0029178a-b4f9-454a-8f29-5eeb1ce2726f.png)

**Comment by Michal-Miky-Jankovsky** [comment]
![Image](https://user-images.githubusercontent.com/7955666/230640951-bbe11428-d515-462e-b0b8-deb5e993c475.png)
![Image](https://user-images.githubusercontent.com/7955666/230640950-49bc3954-3c84-4bab-8a6e-e7eae41c03ca.png)
![Image](https://user-images.githubusercontent.com/7955666/230640952-52f81383-cdc5-4cac-8f1e-41be93df7717.png)
![Image](https://user-images.githubusercontent.com/7955666/230640953-e4180de7-82ba-40a1-9a15-9d0aa9e77693.png)

**Comment by Michal-Miky-Jankovsky** [comment]
prelozeno pres deepl


	"offers.count.offer": "nabídka",
	"offers.count.offers": "nabídek",
	"offers.count.correspondsToYourSearch": "odpovídá vašemu zadání"

	"offers.count.offer": "пропозиція",
	"offers.count.offers": "пропозиції",
	"offers.count.correspondsToYourSearch": "відповідає вашому призначенню"
