### ISSUE TITLE
Nabídky pomoci - zaktivnit odkazy

### ISSUE THREAD

**Issue by hankadev** [cesko-digital/pomahejukrajine-web#142]
Pokud se v nabídce pomoci objeví odkaz na webovou stránku, tak ho udělat aktivním. Při kliknutí na něj ho otevřít v novém okně.

**Comment by Michal-Miky-Jankovsky** [comment]
pattern `http...` / `.cz` as <a href="..."> ???

**Comment by Michal-Miky-Jankovsky** [comment]
www...
http...
...cz
...com

**Comment by ondre28** [comment]
taky .eu, .info
