### ISSUE TITLE
upravy dle figmy - cervene zvyraznene

### ISSUE THREAD

**Issue by Michal-Miky-Jankovsky** [cesko-digital/pomahejukrajine-web#148]
https://www.figma.com/file/ZnHIQwewxB6DyYng4pE1uZ/Pom%C3%A1hej-Ukrajin%C4%9B?node-id=1358%3A13290

**Comment by hanny21** [comment]
dodelat - nabidky:

- [ ] vyhledávací tlačítko presunout pod hlavni nadpis nahoru
- [ ] Pridat prepinani razeni nabidek (Od nejnovejsich/od nejstarsich)
- [ ] pridat prilohy do karty nabidek
- [ ] pridat cas zverejneni/aktualizace nabidky do karty nabidky

**Comment by ondre28** [comment]
Honza už některé věci na backendu zařídil, takže už lze rozjet:

- přidání příloh
- přidání času aktualizace nabídky. Řazení nabídek by bylo defaultně od nejnovějších po nejstarší.

**Comment by ondre28** [comment]
Není přidáno políčko "Všechny nabídky"


![Image](https://user-images.githubusercontent.com/116279861/204503234-4e5ce628-debf-498c-8160-c1f14336999f.png)

**Comment by Michal-Miky-Jankovsky** [comment]
@ondre28 

jsou to rozdilne kategorie obsahu, ne ze by to neslo, ale... 

jaky je use case?

![Image](https://user-images.githubusercontent.com/7955666/205455203-afd410e8-f950-45ea-9319-d9b825248bb5.png)

**Comment by Michal-Miky-Jankovsky** [comment]
to neni filtr ale "podstranky"

**Comment by ondre28** [comment]
Vlastně by to bylo spíš k ničemu, protože by se ve všech nabídkách dalo vyhledávat jen fulltextově a nebo podle kraje/okresu. Každý typ nabídky má totiž trochu jiný filtr.

**Comment by Michal-Miky-Jankovsky** [comment]
ok, diky = done
