### ISSUE TITLE
tlacitko "odstranit filtry"

### ISSUE THREAD

**Issue by hanny21** [cesko-digital/pomahejukrajine-web#152]
![Image](https://user-images.githubusercontent.com/31318129/203821616-9ddd5ade-bff3-489e-8b76-814315a193af.png)

**Comment by ondre28** [comment]
Ahoj Hanko, šlo by prosím tomu textu dát stejnou velikost jak u tlačítka "Potřebuji tuto pomoc"?

**Comment by hanny21** [comment]
> pomoc

slo, ja jsem to tlacitko delala podle designu ve Figme... mam to teda zmenit a nebo si to radeji potvrdit s Davidem?

**Comment by hanny21** [comment]
info od Davida: 
`muze to byt stejne tlacitko jako Potrebuji tuto pomoc, akorat nevyplnene modrou barvou, ale jen s outlinou. Hover efekt bych potom dal snizeni opacity tlacitka treba na 80 % jestli to bude stacit, bez fade in
Na mobilu prosim stejny design tlacitka jako na desktopu.`
