### ISSUE TITLE
Zobrazení informací v moje nabídka

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#162]
Prosím zobrazit dodatečné informace o nabídce uživatelů, když se se přihlásí do svého účtu (Moje nabídky):
kód nabídky a datum poslední aktualizace nabídky. 

![Image](https://user-images.githubusercontent.com/116279861/201039585-603f433f-820c-473b-8e9a-9a6a89af5f33.png)

**Comment by hanny21** [comment]
@ondre28 staci pouze do seznamu mych nabidek a nebo i do editace?


![Image](https://user-images.githubusercontent.com/31318129/208522319-1160995d-8198-4e07-a515-c4cf62909058.png)
![Image](https://user-images.githubusercontent.com/31318129/208522366-af102acf-d836-406a-b884-4be2c8ec1efb.png)

**Comment by ondre28** [comment]
Prosím i do editace.
