### ISSUE TITLE
Pořadí položek ve filtru

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#174]
Ve filtrech je nyní nastaveno, že pokud zaškrtnu políčko ve filtru, tak se ve filtru posune na první místo (obrázek). Prosím aby políčko i po zaškrtnutí zůstalo na stejném pořadí ve filtru. 

![Image](https://user-images.githubusercontent.com/116279861/215464249-b7f2e6bf-d5ef-47b2-86cc-83a1ec21ac99.png)

**Comment by ondre28** [comment]
Hanko, toto ještě není napravené.

**Comment by hanny21** [comment]
> Hanko, toto ještě není napravené.

ono chvili od uzavreni trva, nez se to nasadi na staging :smile:  .. ted uz to je nasazene
