### ISSUE TITLE
Text do formuláře

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#178]
Prosím přidat text do fomuláře, konkrétně po odeslání popvátky po pomoci. Nejedná se o nahrazení textu, pouze o přidání věty.

![Image](https://user-images.githubusercontent.com/116279861/216958849-820e29b5-a9e3-41cd-ac25-533eec4096e8.png)

**Comment by hanny21** [comment]
@ondre28 ahoj, mas k tomu i preklad do ukrajinstiny a nebo staci, kdyz to prelozim pres google translator?

**Comment by ondre28** [comment]
Text v uj dodáme snad brzo.

**Comment by ondre28** [comment]
@hanny21 tady jsou ty texty:
ČJ: Nyní prosím potvrďte svou poptávku kliknutím na odkaz, který jsme poslali do Vaší emailové schránky.
UJ: Тепер, будь ласка,пiдтвердiть свiй запит натиснувши на повiдомлення, яке ми надiслали на вашу електронну адресу.
