### ISSUE TITLE
Nabídky pomoci - info o organizaci

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#179]
Pokud dobrovolník ve formuláři "Nová nabídka" vyplní pole "Organizace", tak aby se řádek zobrazoval na FE v kartě nabídky. 

![Image](https://user-images.githubusercontent.com/116279861/216971844-6c131351-4fd1-480e-99b3-d3305fd1f1c2.png)

**Comment by hanny21** [comment]
cekam na naindexovani dat
