### ISSUE TITLE
pridat stranku Ubytovani

### ISSUE THREAD

**Issue by hanny21** [cesko-digital/pomahejukrajine-web#187]
Pridat novou stranku pro ubytovani (bez formulare - samostatny task)

https://www.figma.com/file/ZnHIQwewxB6DyYng4pE1uZ/Pom%C3%A1hej-Ukrajin%C4%9B?node-id=0%3A1&t=oI0cnb6UssOgDXaU-0

**Comment by ondre28** [comment]
Ještě budeme upravovat na stránce texty, dodám v Čj a Uj.

**Comment by hanny21** [comment]
> Ještě budeme upravovat na stránce texty, dodám v Čj a Uj.

jj, to nevadi... na pridani textu v ukrajinstine mame samostatny task https://github.com/cesko-digital/pomahejukrajine-web/issues/191, tak v ramci toho muzeme potom finalizovat i texty v cestine :wink:
