### ISSUE TITLE
pridat Ubytovani na homepage

### ISSUE THREAD

**Issue by hanny21** [cesko-digital/pomahejukrajine-web#188]
Upravy na homepage (text and boxy, novy box, pridani polozky do navigace) souvisejici s ubytovanim

https://www.figma.com/file/ZnHIQwewxB6DyYng4pE1uZ/Pom%C3%A1hej-Ukrajin%C4%9B?node-id=0%3A1&t=oI0cnb6UssOgDXaU-0

**Comment by ondre28** [comment]
Nový text je i:
- pod navigací (welcome text)
- v boxu Hledám pomoc
