### ISSUE TITLE
Ubytovani - formular a potvrzeni odeslani formulare

### ISSUE THREAD

**Issue by hanny21** [cesko-digital/pomahejukrajine-web#189]
Pridat formular pro vlozeni nabidky na stranku ubytovani + v pripade, ze se jedna o ubytovani, tak zobrazit jinou potvrzovaci hlasku (jedna se o obecnou zmenu pridani nabidky, tedy stejne bude fungovat i pokud zadam nabidku standardnim zpusobem)

https://www.figma.com/file/ZnHIQwewxB6DyYng4pE1uZ/Pom%C3%A1hej-Ukrajin%C4%9B?node-id=0%3A1&t=oI0cnb6UssOgDXaU-0

**Comment by ondre28** [comment]
@hanny21 Jde prosím tě na té stránce udělat to, že by v tom formuláři:
- byla už předem zaškrtnutá kategorie Ubytování?
- byl jiný úvodní text, než u formuláře, na který se uživatelé dostanou klikem na "Nabízím pomoc"?

**Comment by hanny21** [comment]
@ondre28 jj, to by nemel byt problem

**Comment by ondre28** [comment]
Skvělý :-)
