### ISSUE TITLE
Přidat loga nových členských organizací

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#195]
Do seznamu log na homepage přidat 3 loga s aktivními odkazy a na stránce je všechny zarovnat k ostatním.

![Image](https://user-images.githubusercontent.com/116279861/225126172-d695b5e7-6636-4ca4-8138-197b0c1b8eeb.jpg)
https://dignityrh.org/

![Image](https://user-images.githubusercontent.com/116279861/225126194-376ad0bc-8885-4786-8f22-7a965bb3d2c8.png)
http://www.kalyna.cz/

![Image](https://user-images.githubusercontent.com/116279861/225126217-620da8b9-9b20-4a02-b556-8e3dcfe4cdbb.png)
https://czechdoc.cz/cs/

**Comment by ondre28** [comment]
@radomila loga Kalyna a Dignity se tam bohužel nezobrazují ve správných rozměrech.

**Comment by radomila** [comment]
@ondre28 už to vidím - teď by to mělo být v pořádku

**Comment by ondre28** [comment]
@radomila Děkuji, je to ok :-)
