### ISSUE TITLE
pridat formular na stranku ubytovani

### ISSUE THREAD

**Issue by Michal-Miky-Jankovsky** [cesko-digital/pomahejukrajine-web#198]

**Comment by Michal-Miky-Jankovsky** [comment]
kopie formulare - reuse componenty

**Comment by hanny21** [comment]
@radomila existuje jeste task https://github.com/cesko-digital/pomahejukrajine-web/issues/189, ktery se prekryva s timto, prosim muzes poresit oboje?

**Comment by radomila** [comment]
jj, urcite
