### ISSUE TITLE
Spravit filtrování organizací

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#204]
Nefunguje filtrování organizací na FE: https://www.pomahejukrajine.cz/organizace
Možná je ale problém v BE?

**Comment by hanny21** [comment]
@ondre28 bylo to zpusobeno zmenou na BE 2 mesice zpatky.. z pole `district` u organizace se stalo `districts` - cili zmena moznosti pridani vice hodnot, ale na FE se to nezmenilo.. mergnula jsem opravu, az se nasadi aktualni verze na stg tak to muzes zkontrolovat.

**Comment by ondre28** [comment]
@hanny21 děkuji za opravení. Bohužel si to ale vyzkoušet nemůžu, stále se mi nezobrazuje to preview :-(
