### ISSUE TITLE
Ikonka u kategorie nabídky

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#205]
Při přejmenování kategorie nabídky přestala být vidět ikonka (psí tlapa). Prosím o její zobrazení. 

![Image](https://user-images.githubusercontent.com/116279861/238933352-7dcd5523-b5db-4b51-a186-8089e8fac97d.png)

**Comment by hanny21** [comment]
@ondre28 ono ta ikonka se prirazuje v kodu a bohuzel contember nema zadny jiny pouzitelny identifikator nez ten samotny text.. vetsinou byva k dispozici nejaky kod, ktery se da pouzit a nebo se ikonka da definovat,ale taky jsme museli zvolit takove reseni, ze to delame podle textu... neni  to idealni, ale jinak by to bylo hodne prace na BE.

**Comment by ondre28** [comment]
@hanny21 aha, děkuji za vysvětlení. Výhledově chceme přejmenovat ještě jednu kategorii, takže nás tím pádem bude čekat podobný zádrhel.
