### ISSUE TITLE
Korektura stránky Ubytování - 3. kolo

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#211]
Prosím ještě jednou o projetí korektur stránky ubytování na Figmě (korektura 1. kolo 18. dubna 2023), jestli je už vše zapracované. S Davidem Babkou jsme zjistili, že například velikost textu v části "Jak to funguje" je menší, než by měl být. Resp. text by měl být stejně velký jako text na homepage. 
https://www.figma.com/file/ZnHIQwewxB6DyYng4pE1uZ/Pom%C3%A1hej-Ukrajin%C4%9B?type=design&node-id=0-1&t=ByBmy4e5onnkpLww-0

Pokud je korektura zapracovaná, tak prosím odklikni/odfajfkuj ten Davidův koment. Díky!

**Comment by radomila** [comment]
Korektura: 
1) Velikost písma v sekci "Jak to funguje" byla zvětšena na 17px, už by měla tedy odpovídat velikosti písma na homepage 
2) Text pro **Pravidla podpory** v sekci "Podpora ubytování uprchlíků v domácnostech" byl upravený a pro větší přehlednost jsem přidala žluté pozadí, stejně jako v sekci "Jak to funguje" u jednotlivých nadpisů

**Comment by ondre28** [comment]
Ahoj @radomila, korektura je v pohodě, takhle to vypadá dobře. Myslím, že grafik David Babka toho měl víc ([zde na Figmě](https://www.figma.com/file/ZnHIQwewxB6DyYng4pE1uZ/Pom%C3%A1hej-Ukrajin%C4%9B?type=design&node-id=2637-21177&mode=design&t=3WDVGuhEFyCAWjc3-0)), ale za mě je to v pohodě. David našel ještě jednu malou věc na opravu na homepage, tak bych ti k ní udělal task. Je to fakt drobnost.
