### ISSUE TITLE
Home page - linky na naše sociální sítě

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#22]
Uživatelé  na Front page se mohou prokliknout přes zobrazená loga a jim odpovídající linky
 na naše sociální sítě

https://twitter.com/pomahejukrajine
https://www.instagram.com/pomahejukrajine.cz
https://www.facebook.com/PomahejUkrajine.cz/?ref=page_internal

a k tomu ikonky do prvého horního rohu nahoru, viz obrázek 
![image](https://user-images.githubusercontent.com/101886400/160084379-70e75819-90ef-45b4-966e-e4105f21e00e.png)

[https://drive.google.com/drive/folders/1CX7Z2-zUpFL54cwHI-TEhJ6hQo54noTw?usp=sharing](url)

**Comment by tgds** [comment]
@ZdenekMen, moze to byt takto? https://pomahejukrajine-web-git-social-logos-ceskodigital.vercel.app/

**Comment by ZdenekMen** [comment]
@tgds Ahoj Tomáši, děkuji moc - perfektní

**Comment by tgds** [comment]
> @tgds Ahoj Tomáši, děkuji moc - perfektní

super, tak je to mergnute do `mainu`. este to musi @honzasladek nasadit :)
