### ISSUE TITLE
Jednotná dolní část stránky

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#220]
Na Figmě [nahoře vpravo](https://www.figma.com/file/ZnHIQwewxB6DyYng4pE1uZ/Pom%C3%A1hej-Ukrajin%C4%9B?type=design&node-id=0-1&t=qQqw3IXCvd9gB8nz-0) (Homepage - desktop final) je návrh modrého pruhu, který chceme, aby byl zobrazen na všech stránkách platformy Pomáhej Ukrajině. Je tam verze pro desktop i mobil.

**Comment by hankadev** [comment]
@ondre28 a ten pruh dat zatim jenom na Homepage nad ty loga (tj. misto toho modrozluteho pruhu) a nebo i nekam jnam? 


![Image](https://github.com/cesko-digital/pomahejukrajine-web/assets/31318129/c69f5556-44a4-422b-b1e2-3e899691a7c5)

**Comment by ondre28** [comment]
@hankadev Ahoj, chceme ho dát na homepage nad loga a na ostatních stránkách úplně dolů.

**Comment by ondre28** [comment]
@hankadev ten modrý pruh by nahradil současný šedivý pruh v zápatí stránky.
