### ISSUE TITLE
Korektura HP

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-web#224]
Na homepage prosím roztáhnout žlutý pruh až ke konci stránky. Více zde: https://www.figma.com/file/ZnHIQwewxB6DyYng4pE1uZ/Pom%C3%A1hej-Ukrajin%C4%9B?type=design&node-id=3240-30584&mode=design&t=se9eYYShjRXPS1H0-0

**Comment by radomila** [comment]
Určitě, mrknu na to
