### ISSUE TITLE
FE: Create new register fields

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#32]
Pomáhající Organizace při registraci na FE zadává další povinná pole
---------

Pomáhající Organizace při registraci na FE  je přesměrována do Formuláře mimo systém a zadává nová povinná pole Adresa, Okres, Kraj , ICO, WEB, Typ organizace (vybrat z nové tabulky TypOrganizace) a Poznámka (textové pole ).
Tyto pole ověří Administrátor s Konsorcia a zadá je ručně na BE do systému Admin Contember

**Comment by Michal-Miky-Jankovsky** [comment]
blocked by https://github.com/cesko-digital/pomahejukrajine-contember/issues/7

**Comment by ZdenekMen** [comment]
Ahoj, --- prosim rozsirit a další pole " Mateřská Organizace", například Charita Česká republika  pro Charita Třeboň

**Comment by ZdenekMen** [comment]
Přikládám tabulku  Typ Organizace, kterou bude nutno přidat jako nový číselník do BE: 


Školské zařízení
Výzkumný a vysokoškolský sektor
Vládní a veřejná organizace
Soukromý podnik
Ostatní
Osoba - OSVČ
Obec
Nevládní/neziskový sektor
Nadace
Média
Církev
Dobrovolnická iniciativa
