### ISSUE TITLE
FE: Editace osobních dat v Muj Profil

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#43]
Dobrovolník na  FE v části Moje nabídky zvolí 
zda jít do editace  Nabídky, přidá novou nabídku viz #26  nebo na novou Volbu “Upravit svůj osobní profil” a  tím přejde na novou obrazovku (dnes neexistuje) , kde  bude editovat pole o své osobě  - Jméno, Telefon, Můžete mne kontaktovat, Hovořím těmito jazyky, Specifická  odbornost 

Viz můj neumělý návrh , prosím o správné fonty, jako je to dnes a vycentrování 
![image](https://user-images.githubusercontent.com/101886400/167307524-0a8db999-d7a4-4608-b402-bae81e038124.png)

Nová obrazovka bude podobná obsahem a funkcemi vstupní obrazovce  (mimo nabídek)
![image](https://user-images.githubusercontent.com/101886400/167307434-b9eef03b-89f1-43f6-95db-3df09cd75918.png)

**Comment by ZdenekMen** [comment]
Omlouvám se, a posílám aktualizované zadání
 Dobrovolník na  FE v po stisknutí  Můj profil zvolí, zda jít do jedné z Nabídek nebo na novou Volbu “Upravit svůj osobní profil” a   jít na novou obrazovku, kde  bude editovat pole o své osobě  - Jméno, Telefon, Můžete mne kontaktovat, Hovořím těmito jazyky, Specifická  odbornost 

Mail bude zobrazen ale nelze jej editovat
![image](https://user-images.githubusercontent.com/101886400/161544377-7f9c20ee-1f60-44c2-b0d1-78e7670e7e1a.png)

**Comment by ZdenekMen** [comment]
oplneni informace - pri zobrazeni nabidek v leve casti obrazovky se ukazou i jejich parametry, to je ale jiz soucasna funkcnost, i kdyz nekdy chybova (hlaseno jako provozni chyba na tym Contemeber)
viz

![image](https://user-images.githubusercontent.com/101886400/164722163-8f314648-8d74-45eb-b2e7-5959f8af7ed3.png)

**Comment by matej-sveda** [comment]
@ZdenekMen z toho obrazku s sipkama to vypada, jakobychom u dalsi navidky nechteli vyplnovat pole “Co mohu nahidnout”…tomu ale moc nerozumim, nemelo by tohle pole byt povinne u kazde nabidky?

**Comment by ZdenekMen** [comment]
@matej-sveda Ahoj Mateji, good questin, tak ja to rikas je to na prvni vstupni  obrazovce , kde se dela oboje tj zalozi profil a pridava nabidka. 
Tady  v "Moje nabikdy pomoci"  je prave rozcestnik bud na 1. editaci nabidek,  2. pridavani nabidky (jine issue)  NEBO POUZE 3. EDITACE PROFILU, Zde se resi poze osobni tj ne-nabidkve veci.  Prosim te, je to tak jasne? Moc a moc dekuji

**Comment by matej-sveda** [comment]
> @ZdenekMen diky za vysvetleni, i v issue je to vysvetleno pekne, ja si toho pak vsimnul, tak jsem ten komentar smazal... mel jsem ho radeji upravit :D vsechno je to jasne :+1:

**Comment by ZdenekMen** [comment]
;-) a ja jsem se divil, ze to memuzu najit

**Comment by ZdenekMen** [comment]
Ahoj @martinsik , diky moc, funguje to perfektne.  Mrknul jsme i na ukrajinskou verzi - kde zustavaji nejake ceske casti, to snad doresi postupne Hana 
![image](https://user-images.githubusercontent.com/101886400/171357986-c5d658cd-3c74-441e-9ea1-9a7b725547de.png)
![image](https://user-images.githubusercontent.com/101886400/171358117-321f648b-30b3-49ac-8940-f073ddcbca49.png)
@honzasladek Honzo, proism te, bud tak hodny, posud to a dej na Produkci. 
DEKUJI VSEM

**Comment by honzasladek** [comment]
Nasazeno.

**Comment by ZdenekMen** [comment]
Ahoj pánové @honzasladek @martinsik , děkuji moc za nasazení. Funkčně je to perfektní. Při otevření mi to ukázalo jméno, specializaci i další poznámky v ukrajinštině. Může to ale být tím, že jsem přes víkend / moc brzy/ testoval ukrajinštinu a nějak jsem to zamotal. zkusím sehnat další lidi, ať se na to podívají.


![Image](https://user-images.githubusercontent.com/101886400/171801700-47df800d-2520-41c1-b3b7-70b73ce37007.png)

**Comment by ZdenekMen** [comment]
Ahoj pánové, @honzasladek @martinsik dalšímu člověku to chodí bez problému. Děkuji, omlouvám se a toto Issue zavíráme
