### ISSUE TITLE
Redesign Homepage except of header

### ISSUE THREAD

**Issue by george-cz** [cesko-digital/pomahejukrajine-web#45]
There is a different task for the header part of homepage (#44). This one is about the rest:

![image](https://user-images.githubusercontent.com/2070479/161776095-0d97fbc4-058a-47fc-80f2-e1e9447b7c5d.png)

- This should be responsive
- Figma link: https://www.figma.com/file/ZnHIQwewxB6DyYng4pE1uZ/Pom%C3%A1hej-Ukrajin%C4%9B?node-id=0%3A1
- The logos are freshly done, just take care of the responsiveness there

**Comment by ZdenekMen** [comment]
Ahoj @hanny21 , moc se omlouvam, prosim o zmenu textu (to presne vyjmenovani byla hloupost) na vice obecny text  . Moc dekuji 

Cast Nabízím pomoc
Zde můžete vložit svou nabídku. Některé nabídky, například materiální pomoc, ale i některé služby, budou okamžitě zveřejněny a využít je může kdokoli. S ostatními nabídkami pracují pouze registrované pomáhající organizace. 

Cast Hledám pomoc
Zde můžete vyhledat materiální pomoc, nebytové prostory, dopravu nebo některé služby a přímo o ně požádat. Potřebujete-li využít jiné typy pomoci, kontaktujte vhodnou pomáhající organizaci.
