### ISSUE TITLE
FE: možnost vyhledávání na FE - pro současnou obrazovku Nabidky pomoci 

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#50]
uživatel na FE - na obrazovce nabídky pomoci může pro veřejné nabídky zadat v části Více filtrů do pole “Vyhledej text”  hledaný text např. matrace, který se bude vyhledávat v rámci již zadaných filtrů

Nabídky budou aktualizovány o výsledky tohoto hledání 
  
![image](https://user-images.githubusercontent.com/101886400/162745746-7bc7842d-6ca9-4e17-878f-560fb75cd24b.png)

**Comment by ZdenekMen** [comment]
@hanny21 Ahoj Hani, omlouvám se, toto Issue jsem v pátek ráno stáhnul z Todo do Backlogu - zatím jsem to pozastavil, pánové z Contember slíbili, že pro to něco ještě  na začátku května dodělají.  Měl jsme to sem asi zapsat.  Prosím tě,  jak jsi se dostala daleko?

**Comment by hanny21** [comment]
@ZdenekMen Ahoj, zatim jsem na tom v podstate nezacala, jenom jsem koukala, jak to funguje v soucasnosti.. hodim to zpatky do backlogu a budu se tomu teda venovat pozdeji :wink:

**Comment by ZdenekMen** [comment]
uffffff, děkuji moc, byl jsem z toho špatný

**Comment by ZdenekMen** [comment]
zruseno
