### ISSUE TITLE
Vyhledávání v seznamu Organizaci

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#61]
Uzivatel FE hledá v seznamu všech pomáhajících  Organizací dle Kraje, Okresu, Obec,  a Textove (napr vsechny Charity)

Vývoj může začít po dokončení Issues na BE, např https://github.com/cesko-digital/pomahejukrajine-web/issues/32 - Hotovo  a zavest do provozu společně s  #60. 

Nabídka bude zobrazena na Front page #60 , kde jsou tyto organizace zmíněny a dále bude pokračovat následná navigace:
1.	Zobrazení kompletního seznamu všech organizací formou tabulky. Zde by se mělo zobrazit  Název, Adresa, ICO, Materska organizace, Typ organizace. Zkuste prosim, jak se to rozumne vejde na stranku, pripadne ty delsi veci zalomit.  Bylo by super, kdyby se pri kliknuti na Nazev preslo na web organizace (je tam jako samostane pole), pokud by to neslo, tak to www pridat jako sloupec  s moznosti prokliku 
2.	Vyhledávání prostřednictvím filtrů pro Kraje, Okresy, Obce, Mateřské organizace nebo prostřednictvím hledání zadaného textu. Dle těchto filtrů se postupně zužuje nabízený seznam. Viz další komentář
Pro vasi predstavu - na obrazku je videt struktura a obsah 1 organizace 
![image](https://user-images.githubusercontent.com/101886400/167084310-09fe86bb-97e8-49dd-9b66-d814986a09aa.png)

 Druhou možností bude hledání prostřednictvím mapy. Tuto variantu připravujeme paralelně a zasuneme jí jako link na pomahejukrajine.cz

**Comment by ZdenekMen** [comment]
Struktura seznamu - viz #32  nebo dle pracovniho excelu, prosim po zahajeni praci se mi ozvete a ja Vam tam dam pristup - viz obrazek 
![image](https://user-images.githubusercontent.com/101886400/166930240-50ec68e5-1e94-45a2-b8c3-c8db0661895c.png)


Hledání Organizací dle Materske Organizce,  Kraje, Okresu, Obce, bude pomoci **Filru** s postupnum ukazovanim organizici dle vybrane kombinace filtru  - podobne jako na obrazovce Nabidky pomoci viz obrazky   a jako Textove  vyhledavani pres vsechna  pole (napr vsechny Charity)
![image](https://user-images.githubusercontent.com/101886400/166931677-b038744f-7f3b-4f93-9d88-42c18d4685e3.png)
![image](https://user-images.githubusercontent.com/101886400/166931878-253c04bf-0920-4576-87b9-79212c52fcc9.png)

**Comment by ViliamV** [comment]
@ZdenekMen prosim ta:
>  Organizací dle Materske Organizce, Kraje, Okresu, Obce, bude pomoci Filtru 

k tomu mam 2 otazky:
1. Materska organizace je "text field" kde moze byt lubovolna hodnota - naozaj na to chceme mat *Filter*? Tym padom, sa moze stat, ze kazda organizacia tam bude mat nieco vlastne
2. Pole `Obec` nie je v datovom modeli pre Organizaciu - planuje sa to pridat?

**Comment by ZdenekMen** [comment]
Ahoj Viliame @ViliamV 

good questions, děkuji 
1. ano - i když máš pravdu , že to nebude často používané, dobrý příklad je Charita ---- ale ještě tvou dobrou otázku ověřím
2. hmmmm - omlouvám se, tak to jsme se nějak nesladili - stále se o tom mluví, že to bude zajímat Hasiče, kteří jedou jen dle obcí --- asi to nebude --- ale také ti dám brzy vědět.
Uvědomil jsem si že jsme v tom fofru na tobě nechali celý grafický design, tak se těším, hvízdni až to bude nějak vypadat a domluvíme se. Neboj nebudeme prudit, jen nabízím brzký feedback

**Comment by ZdenekMen** [comment]
Ahoj @ViliamV - dohodli jsme se na rychly, jednduchy postup tj
1. Bez filtru na Materske organizace
2. Bez Obce
To vse se muze pokryt tim Vyhledavanim dle textu . OK? dekuji
