### ISSUE TITLE
Kontrola PSČ pro Ubytování

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#63]
Dobrovolník na FE nabízí adresu ubytování včetně PSČ  = prosím kontrolovat na 5 znaků a numeriku

![image](https://user-images.githubusercontent.com/101886400/167267035-9dba04a3-dbb7-4ca1-a417-92205333abdd.png)

**Comment by marrtan3** [comment]
@ZdenekMen @martinsik tento task jsem už udělal a je ve stavu pull request

**Comment by ZdenekMen** [comment]
@marrtan3 , Martine moc diky, ja se tesim az mi to nekdo zpristupni na Stage

**Comment by ZdenekMen** [comment]
@marrtan3 Martine, perfektní, krásně to maká 
@honzasladek Honzo, prosím tě, až budeš nasazovat další balíček, přihoď to k tomu.
DĚKUJI VÁM OBĚMA
