### ISSUE TITLE
Uzivatelská editace textu na platformě 

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#67]
Bylo by velmi prospěšné, aby Administrátor platformy v Konsorciu mohl editovat například FAQ,  Nápovědy ap. ,které se zobrazují na FE 

Prosím Vás, jaké jsou na to možnosti?  Navrhněte a poraďte. DĚKUJI

**Comment by ZdenekMen** [comment]
doporuceni od Honzy Sladka na Slacku
[Honza Sládek](https://app.slack.com/team/UJQPL2VPT)  [26 minutes ago](https://cesko-digital.slack.com/archives/C037PUF48EM/p1652345754933819?thread_ts=1652285447.888979&cid=C037PUF48EM)
**Tohle je v Contemberu na ~20 minut zhruba.
Přidají se jednotlivé entity (tj. FAQ, otázky) a udělá se <MultiEditPage/> kde se ty věci budou editovat a přidá se public roli, že toto může číst.**





Honza Sládek  26 minutes ago
Richtext a všechno Contember má k dispozici, takže nevidím nikde problém.

**Comment by VanaMartin** [comment]
Pripojil jsem [PR 25](https://github.com/cesko-digital/pomahejukrajine-contember/pull/25) ve kterem je backend implementace editovatelnych poli pro FAQ. Predpokladal jsem ze je treba mit v entitach jak ceskou tak ukrajinskou verzi.
Pokud chceme jese dalsi entity, prosim o specifikaci, pripadne zda chceme sjednotit nejakym zpusobem jejich backend podobu, nebo zda je za vas v poradku drzet kazdy typ ve vlastni entite.

**Comment by VanaMartin** [comment]
Rikladam screenshot
![image](https://user-images.githubusercontent.com/23655973/170364612-cc964497-5b5f-4c5e-a0e9-a63204887994.png)

**Comment by ZdenekMen** [comment]
Ahoj @VanaMartin , díky moc za perfektní a rychlou práci v prostředí Contember. Pro tuto entitu je to super. Na jiné se zeptám v konsorciu, Prosím tě, dopady této změny do FE zajistíš také ty nebo máme někoho hledat? Já bych ocenil tu první variantu. Přeji pěkný den.

**Comment by VanaMartin** [comment]
Na frontend se zkusi kouknout. Jakmile budeme mit mergnutou tuto zmenu, musime nejprve preklopit existujici otazky na backend, tj do databaze. Pak az muzeme propagovat zmenu na "web". To plati pro vsechny entity, tedy tento task by mel mit tri faze: BE, migrace a FE.

**Comment by ZdenekMen** [comment]
@VanaMartin Martine, moc díky, rozumím a hlásím se na migraci.
