### ISSUE TITLE
Povinné podle telefonní číslo při registraci dobrovolníka

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#7]
Všichni uživatelé platformy by měli být mezi být dostupní i přes svůj telefon 

Uživatel na Front Endu má  dnes při  registraci povinný jen Mail. Pro další komunikaci je třeba nastavit, že i Telefon bude povinný

**Comment by ZdenekMen** [comment]
![image](https://user-images.githubusercontent.com/101886400/159712190-c7ba8e69-6fbe-4902-b7da-29215d9c20f4.png)

**Comment by george-cz** [comment]
on it

**Comment by george-cz** [comment]
on it

**Comment by george-cz** [comment]
Jake mame pozadavky na format toho cisla? Ono zvalidovat telefonni cislo neni jen tak. Staci, kdyz to bude jen required ale nebudeme testovat format?

**Comment by ZdenekMen** [comment]
Ahoj Jirko, rozumim, ANO - takto to staci DEKUJI MOC

**Comment by ZdenekMen** [comment]
Jirko, perfektní, díky moc, otestováno v Stage - OK, prosím @honzasladek  Honzu o Deploy na Produkci

**Comment by ZdenekMen** [comment]
Ahoj panove, @honzasladek @george-cz omlouvam se , tady je to zavrene ale na produkci to jeste neni. Prosim Vas, co s tim? DEKUJI

**Comment by honzasladek** [comment]
@ZdenekMen Nedostal jsem se k tomu včera, takže jsem nasadil až teď. Je to na produkci.
