### ISSUE TITLE
Zmena log a linku na Home page 

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#9]
Uživatelé  na Front page se mohou prokliknout na další členy konsoricia přes zobrazená loga a jim odpovídající linky

![image](https://user-images.githubusercontent.com/101886400/159723580-3ba5b1cb-7943-45fb-aa8a-41e555d978cb.png)

[https://docs.google.com/spreadsheets/d/1Ee7xbdSwwqrN8oMp5Po9nEIN-E708-PYhMPI5FheIuI/edit?usp=sharing](url)

tady jsou loga 

[https://drive.google.com/drive/folders/1r_7uACjKRMz8VyQu7uEf0_V9HHcB44-J?usp=sharing](url)

**Comment by tgds** [comment]
on it

**Comment by tgds** [comment]
@ZdenekMen tu je preview: https://pomahejukrajine-web-git-fork-tgds-add-logo-links-ceskodigital.vercel.app/

**Comment by ZdenekMen** [comment]
@tgds Tomasi, dekuji jsi 1!!!
Vypadá to dobře 
Za mne OK prosím tým Contember  @honzasladek o deploy do Produkce.

Pocitam s tim, ze potom to zavru
Dekuji vsem

**Comment by honzasladek** [comment]
Vidím. Můžeme se prosím domluvit, že když to bude schváleno, tak to mergnete a my pak nasadíme? cc @tgds @Michal-Miky-Jankovsky

**Comment by tgds** [comment]
@honzasladek je to v main 👍

**Comment by honzasladek** [comment]
Díky! Jdu to nasadit

**Comment by honzasladek** [comment]
Nasazeno @ZdenekMen
