### ISSUE TITLE
Testovani ukrajinstiny - mail pro hledajicho

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-web#91]
Mail, ktery prijde Zadateli o pomoc je cesky, i kdyz je to vyvolano z  UA verze  
preklad  Доброго дня, для передачі контактних даних людині, яка пропонує допомогу, будь ласка підтвердьте ваш е-мейл. Просто натисніть посилання нижче:

![image](https://user-images.githubusercontent.com/101886400/169810980-5370b952-f968-458c-bff0-5bf38629711c.png)

a po proklinuti tohoto mailu to jde opet, logicky, na ceskou verzi obrazovky
![image](https://user-images.githubusercontent.com/101886400/169811157-c0d239da-6049-448c-9b86-d851b3b5dfa7.png)

**Comment by hanny21** [comment]
@ZdenekMen otazka, jak to resit, napadaji me 2 moznosti:
1. mit jeden email a v nem obe jazykove verzi s tim, ze ta ukrajinska bude mit link na ukrajinskou verzi webu.. coz bude asi docela rychle na implementaci
2. mit jiny email pro kazdy jazyk, ale nevim, jak moc pracne by to bylo, to bude vedet spis @Michal-Miky-Jankovsky

**Comment by ZdenekMen** [comment]
Ahoj @hanny21 , hosi se nezvali - prosim te, tak hlasuji pro variantu dvojjazycneho mailu . MOC DEKUJI

**Comment by martinsik** [comment]
@hanny21 Ja jsem se dival jak jsou ty emaily ted ulozene we workeru https://github.com/cesko-digital/pomahejukrajine-worker/blob/main/src/email.ts. Ono si to uz ted dotahuje z Contemberu adresy kam potrebuje poslat emaily, ale nevim jestli se k uzivatelum uklada nejaky priznak jestli se registrovali z UK nebo CZ verze.

**Comment by honzasladek** [comment]
Pokud to tam někdo nepřidával v nějakém PR, tak příznak pro uživatele CZ/UK zatím není.
